spring:
  application:
    name: admin-service
server:
  port: 8871
eureka:
  instance:
    ip-address: 127.0.0.1
    port: 8761
    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.ip-address}:${eureka.instance.port}/eureka/
ribbon:
  eureka:
    enabled: true

zuul:
  routes:
    static:
      path: /static/**
      url: http://localhost:8001/
    auth-service:
      sensitiveHeaders:
      path: /auth/**
      stripPrefix: false
    exam-service: /exam/**
    admin-service: /admin/**
  add-proxy-headers: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
security:
  user:
    password: none
  oauth2:
    client:
      accessTokenUri: http://localhost:8871/auth/oauth/token
      userAuthorizationUri: http://localhost:8871/auth/oauth/authorize
      clientId: web-app
      preEstablishedRedirectUri: http://localhost:8871/login
      registeredRedirectUri: http://localhost:8871/login
      useCurrentUri: false

    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAimUKhvBhsoeSM3HkIOP/Y3RXjvonBlZnLj8oO92TyAKG53lmAoK0wZ5MTZPsfrOz2Z7CeAp6mPhUANX2RUoFwVzG7rJmgWyqGmGFNBmtYL+uVqQ80TzWi5zyzXTxgVMWiCqqw/u4AeE1qhN8chnGwhUBnpgPAPd8v57mIwg0n5JxjdYe7pgHlpvt8ZXTXd1KBxB5K7WjNlCfMf75ZEeBaplxsSfJUwKbnHQKWcY3NnpjkVR8y4jviAbkOHmGMaliM7fcsLzbosBUPDQuNlvYdjPBRfH6MMPeXRW6On3u0Um9wIYmkQS+AEgHCq4UuLOnTTqqxnGkwFYeMAAXmRyMtQIDAQAB
          -----END PUBLIC KEY-----

logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
    com:
      tangyi:
        mapper: DEBUG

